server.port: 8866
solon.serialization.json:
  dateAsFormat: 'yyyy-MM-dd HH:mm:ss' #配置日期格式（默认输出为时间戳）
  dateAsTimeZone: 'GMT+8'
  dateAsTicks: false #将date转为毫秒数（和 dateAsFormat 二选一）
  longAsString: false #将long型转为字符串输出 （默认为false）
  boolAsInt: false   #将bool型转为字符串输出 （默认为false）
  nullStringAsEmpty: false
  nullBoolAsFalse: false
  nullNumberAsZero: false
  nullArrayAsEmpty: false
  nullAsWriteable: false #输出所有null值
  enumAsName: true #枚举使用名字（v2.2.1 后支持）
solon.app:
  name: 'anno-admin'
  group: 'DEFAULT'
solon.mime:
  yml: "text/html"
  json: "application/json"
#设定最大的请求包大小（或表单项的值大小）//默认: 2m
server.request.maxBodySize: 100mb #kb,mb
solon.logging.appender:
  console:
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %magenta(${PID:-}) --- %-15([%15.15thread]) %-56(%cyan(%-40.40logger{39}%L)) : %msg%n"
  file:
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level ${PID:-} --- %-15([%15.15thread]) %-56(%-40.40logger{39}%L) : %msg%n"
# 记录器级别的配置示例
solon.logging.logger:
  "root":  #默认记录器配置
    level: info
  "site.sorghum":
    level: debug
  "tech.powerjob":
    level: warn
  "MONITOR_LOGGER_WORKER_HEART_BEAT":
    level: warn
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: anno-token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  is-print: false
db.main:
  schema: anno_admin_demo
  jdbcUrl: jdbc:mysql://localhost:3306/anno_admin_demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456
anno-admin:
  apiServerUrl: http://localhost:8866
  redis:
    server: "localhost:6379"
    db: 8
    maxTotal: '200'
    password: ''
  # 自动初始化数据，默认为 true
  isAutoMaintainInitData: true
  # 自动初始化表，默认为 true
  isAutoMaintainTable: true
  # 是否打印执行的 sql
  showSql: true
  # 忽略打印日志的表
  skipTable: [an_anno_menu,pj_app_info,pj_container_info,pj_instance_info,pj_job_info,pj_oms_lock,pj_server_info,pj_workflow_info,pj_workflow_instance_info,pj_workflow_node_info]
  # 忽略打印请求日志的路径
  skipPathPattern : [/anno-admin-api/assets/**, /server/acquire]


# powerjob-server
powerjob-server-solon.version: @project.version@
###### PowerJob transporter configuration  ######
# AKKA,HTTP
oms.transporter.active.protocols: HTTP
oms.transporter.main.protocol: HTTP
oms.akka.port: 10086
oms.http.port: 10010
####### Cache properties #######
oms.instance.metadata.cache.size: 2048
####### Resource cleaning properties #######
oms.instanceinfo.retention: 7
oms.container.retention.local: 7
oms.container.retention.remote: -1
####### Threshold in precise fetching server(0~100). 100 means full detection of server, in which #######
####### split-brain could be avoided while performance overhead would increase. #######
oms.accurate.select.server.percentage: 50

# powerjob-worker
solon.powerjob:
  # 把原生的关闭掉
  enabled: false
# 使用新的powerjob配置，主要是将 powerjob-worker 的启动放到最后
solon.powerjob2:
  # Whether to enable PowerJob Worker, default is true
  enabled: true
  # Address of PowerJob-server node(s). Ip:port or domain. Multiple addresses should be separated with comma.
  serverAddress: 127.0.0.1:${server.port}
  # Application name, used for grouping applications. Recommend to set the same value as project name.
  appName: ${solon.app.name}
  # If use PowerjobClient to submit a job, you need to set this property.
  password: 123
  # Transport port, default is 27777
  port: 28888
  # transport protocol between server and worker
  protocol: http
  # Store strategy of H2 database. disk or memory. Default value is disk.
  storeStrategy: disk
  # Max length of result. Results that are longer than the value will be truncated.
  maxResultLength: 4096
  # Max length of appended workflow context . Appended workflow context value that is longer than the value will be ignore.
  maxAppendedWfContextLength: 4096
# powerjob-server log storage
oms.storage.dfs.mysql_series.enable: true
oms.storage.dfs.mysql_series.driver: ${db.main.driverClassName}
oms.storage.dfs.mysql_series.url: ${db.main.jdbcUrl}
oms.storage.dfs.mysql_series.username: ${db.main.username}
oms.storage.dfs.mysql_series.password: ${db.main.password}
oms.storage.dfs.mysql_series.auto_create_table: true
oms.storage.dfs.mysql_series.table_name: pj_files

# warm-flow工作流配置
warm-flow:
  # 是否显示banner图，默认是
  banner: false
  # 填充器 （可配置文件注入，也可用@Bean/@Component方式）
  data-fill-handler-path: com.ruoyi.system.handle.CustomDataFillHandler
  # 全局租户处理器（可配置文件注入，也可用@Bean/@Component方式）
  tenant_handler_path: com.ruoyi.system.handle.CustomTenantHandler
  # 是否开启逻辑删除
  logic_delete: true
  # 逻辑删除字段值（开启后默认为2）
  logic_delete_value: 1
  # 逻辑未删除字段（开启后默认为0）
  logic_not_delete_value: 0
  # 当使用JPA时指定JpaPersistenceProvider
  jpa_persistence_provider: org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider
  # 数据源类型, mybatis模块对orm进一步的封装, 由于各数据库分页语句存在差异,
  # 当配置此参数时, 以此参数结果为基准, 未配置时, 取DataSource中数据源类型,
  # 兜底为mysql数据库
  data_source_type: mysql
