spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/anno_admin_demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
  mvc:
    static-path-pattern: /anno-admin/**
  web:
    resources:
      static-locations: classpath:/WEB-INF/anno-admin-ui/
  messages:
    basename: i18n/messages
  freemarker:
    template-loader-path:
      - classpath:/WEB-INF/templates/
      - classpath:/templates/
    suffix: .ftl
anno-admin:
  redis:
    server: "127.0.0.1:6379"
    db: 9
    maxTotal: '200'
  # 主题：antd,cxd,ang
  theme: 'antd'
  # 忽略打印请求日志的路径
  skipPathPattern:
    - /anno-admin/assets/**
    - /anno-admin/index.html
server:
  port: 8855
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: anno-token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  is-print: false