spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sorghum2021
    url: jdbc:mysql://sorghum-ubuntu:3306/anno_admin?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
  mvc:
    static-path-pattern: /anno-admin-api/**
  web:
    resources:
      static-locations: classpath:/WEB-INF/anno-admin-ui/
  messages:
    basename: i18n/messages
anno-admin:
  redis:
    server: "127.0.0.1:6379"
    db: 9
    maxTotal: '200'
  # 主题：antd,cxd,ang
  theme: 'antd'
  # 忽略打印请求日志的路径
  skipPathPattern: [ /anno-admin-api/asserts/**, /server/acquire ]
  apiServerUrl: http://localhost:8855

server:
  port: 8855